version: "2"
services:
  web:
    build: .
    image: ctftraining/wdb_2020_web_qinglong_notes
    restart: always
    ports:
      - "8083:80"
    environment:
      - FLAG=ctftraining{wdb_2020_web_qinglong_notes}
